// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzGeAQUBTjt6JiMvKxea7KMyJgU-tY5m0',
    appId: '1:785961629265:web:e070590d8efda128336a70',
    messagingSenderId: '785961629265',
    projectId: 'daisy-c1c2c',
    authDomain: 'daisy-c1c2c.firebaseapp.com',
    storageBucket: 'daisy-c1c2c.appspot.com',
    measurementId: 'G-BQW4LZNC98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW78xr-oijJzhAuCgX3bnt-ey-p_zDi-k',
    appId: '1:785961629265:android:1ad2feaae632e5f2336a70',
    messagingSenderId: '785961629265',
    projectId: 'daisy-c1c2c',
    storageBucket: 'daisy-c1c2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoy6B1pLUkCMd1WjgvlhJqnShdoIr3tsM',
    appId: '1:785961629265:ios:486bcb3bbd4d11cc336a70',
    messagingSenderId: '785961629265',
    projectId: 'daisy-c1c2c',
    storageBucket: 'daisy-c1c2c.appspot.com',
    iosBundleId: 'com.example.daisy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoy6B1pLUkCMd1WjgvlhJqnShdoIr3tsM',
    appId: '1:785961629265:ios:486bcb3bbd4d11cc336a70',
    messagingSenderId: '785961629265',
    projectId: 'daisy-c1c2c',
    storageBucket: 'daisy-c1c2c.appspot.com',
    iosBundleId: 'com.example.daisy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzGeAQUBTjt6JiMvKxea7KMyJgU-tY5m0',
    appId: '1:785961629265:web:795bef6cac4a28be336a70',
    messagingSenderId: '785961629265',
    projectId: 'daisy-c1c2c',
    authDomain: 'daisy-c1c2c.firebaseapp.com',
    storageBucket: 'daisy-c1c2c.appspot.com',
    measurementId: 'G-2H8C5Q1BPW',
  );
}
